
CALL SQLJ.REMOVE_JAR('SPLICE.APL_CDC_DEMO', 0);

CALL SQLJ.INSTALL_JAR('/tmp/APL_CDC_Demo.jar', 'SPLICE.APL_CDC_DEMO', 0);

CALL SYSCS_UTIL.SYSCS_SET_GLOBAL_DATABASE_PROPERTY('derby.database.classpath', 'SPLICE.APL_CDC_DEMO');
 
